### ISSUE TITLE
Arduino Code

### ISSUE THREAD

**Issue by Tomtom93** [AlanFord/self-balancing-stick#1]
Hello Alan,

I currently working on the Inverted Pendulum Reaction Wheel Project but I have few issues to fix like fix the PID gains for the controller.
First, did you use Pololu or Mitsumi motor in your code "Controller 3.0" ?
How did you calculate theta Kp, Kd and Ki and omega Kp, Kd and Ki ? What is theta and omega Ks, Kt and Kd ?
In fact, I have made a matlab model but I only have PID gains for the entire system..

Thank you for your time and thanks for reply.

Thomas R

**Comment by AlanFord** [comment]
Hey Thomas,
You may be further along than I am - this is still a work in progress.  I had to teach myself control systems theory to figure out if the system would work with the parts I could find.  I'm now learning CNC to machine the components I need.  The code in Controller 3.0 is mostly the original Mike Rouleau code designed for the Mitsumi motors.  I'm using Pololu 25D 4:1 motors.  The derivation of the "K's" for my soon-to-be system can be found in the file latex/writeup-new.pdf.  I haven't looked at it in a while, but it looks like  theta Kp=266, theta Kd=1/4.5, and omega Kp=0.075.  Doesn't look like it needs the other constants.  (My notation is the pdf is a little sloppy - I'm still new to the control theory thing.) These constants are tied to the motor properties.  Also, the friction factor for my motors are different as they are geared motors - both the coulomb and viscous friction are significant (Appendix D of the pdf).  But in summary - Mike said he just adjusted the feedback constants by hand - impressive!

**Comment by Tomtom93** [comment]
Ok thank you very much.
Does the program Controller 3.0 works with your Pololu motors 
?

**Comment by AlanFord** [comment]
They work with the motors.  Balancing will be tested when I get the reaction wheels fabricated.

**Comment by Tomtom93** [comment]
Thank you for the clarification.

Have a good day,

Thomas.

**Comment by simonbogh** [comment]
Hi @AlanFord 

Did you get your project to work, does it balance? 😊 Thinking of building one myself.

How important do you think the encoder CPR/PPR is in your project compared to Mike's original, yours  48 CPR vs. 334 PPR?

**Comment by AlanFord** [comment]
> Hi @AlanFord
> 
> Did you get your project to work, does it balance? 😊 Thinking of building one myself.
> 
> How important do you think the encoder CPR/PPR is in your project compared to Mike's original, yours 48 CPR vs. 334 PPR?

Still working on it - had to pause the project while I teach myself metal machining.  That has been slow going, so I may farm out machining the reaction wheels to a local shop next week.

I don't think the encoder CPR/PPR is that significant, given the rotation speeds that occur.  Of more significance is the torque/speed of the motor.  Since balancing is tied to the wheel acceleration, a high top-end RPM is useful.  My motors don't have a really high top-end, so I will have to focus on slowly decreasing RPM when possible to keep the motor from topping-out.
