### ISSUE TITLE
Program does'nt work properly 

### ISSUE THREAD

**Issue by dhiamaulana** [AlanFord/self-balancing-stick#2]
Hallo, I am a student from Indonesia. I would like to inquire about this program that can not run properly on my Arduino IDE. **expected id-expression before '==' token** In one of the coding _5_interrupts, what should i do? Thanks sir

**Comment by AlanFord** [comment]
I don't  seem to have the same problem - could it be that we are using different versions of the Arduino IDE?  I'm working with Arduino 1.8.7.  I'm working on a Mac, but that shouldn't make a difference.

**Comment by dhiamaulana** [comment]
![Screenshot (99)](https://user-images.githubusercontent.com/49151793/59845172-e9dd3580-9386-11e9-83e3-7d50f60d9dbf.png)
here's the problem i have been asked to you, sir. I don't know, what's word i change or added on your programs, cause every single act to create some new program on interrupt at the top of the programs, it doesn't work. Thank's sir for your respond

**Comment by AlanFord** [comment]
It could be a couple of things.  (Sorry if you know all these things already - it may be new to some people.) First, the *.ino files are compiled in alphabetical order, so the Setup file (where PCintPort is declared) must be named so it is compiled before the Interrupts file.  Hence the file names _3_Setup.ino and _5_Interrupts.ino.  Changing the file names can break the compilation sequence.

It may also be that you need to install the PinChangeInt library.  This is different from the library found in the Arduino standard libraries.  The PinChangeInt library is found at https://github.com/GreyGnome/PinChangeInt

I hope this helps!

**Comment by dhiamaulana** [comment]
Ok, Sir. Thanks a lot for the help. I'll learn from your code and your project's greater than any project i have been seeing, i'm watching your next project, sir. Sorry for bother you all time to help me :D
