### ISSUE TITLE
Ask about using anohther motor DC 

### ISSUE THREAD

**Issue by illgetmyluck** [AlanFord/self-balancing-stick#3]
can i use High Speed Motor DC 25GA370 12V 1000RPM w/ Encoder to change your pololu motor? Thanks

**Comment by AlanFord** [comment]
It should work.  If you begin to approach the maximum RPM when balancing, you may wish to use slightly heavier reaction wheels.

**Comment by illgetmyluck** [comment]
![motor dc encoder](https://user-images.githubusercontent.com/52389711/60862600-37431900-a248-11e9-85bc-8841bb0be457.png) 

![layout balancing](https://user-images.githubusercontent.com/52389711/60863808-04028900-a24c-11e9-8fc3-fdf1e188812e.PNG)

what should I wiring on arduino to change your pinout from pololu motor to arduino board? On your wiring picture, there's ' encoder ' and ' encoder interrupt ' it's same, mister? Sorry about asking you many question. Thanks Mister Alan

**Comment by illgetmyluck** [comment]
what's meaning wire of current - L and current - R . Sorry mister, I didn't know how to wiring that red sign of current. Thanks

**Comment by AlanFord** [comment]
> what should I wiring on arduino to change your pinout from pololu motor to arduino board? On your wiring picture, there's ' encoder ' and ' encoder interrupt ' it's same, mister? Sorry about asking you many question. Thanks Mister Alan

Most encoders have two phases and each will generate signals when they change states (between high and low).  It's best to assign a software interrupt to both - you get the most accurate sensing of the motor position.  Unfortunately, the Arduino Uno only supports two interrupts that can be triggered by an external sensor; these interrupts are tied to Digitial Pins 2 and 3.  Thus, one phase of each motor is connected to either Digital Pin 2 or Digital Pin 3. The second phase of each encoder is then connected to any available input pin.  In your figure Encoder Interrupt would be Encoder A Phase from each motor, connected to either Pin 2 or 3.  The Encoder (B) is the B Phase connection from each motor, connected to Arduino pins A2 and digital 4.

**Comment by AlanFord** [comment]
Current - L and Current - R would be connected if the Arduino is being used to directly measure the current supplied to the left and right motors, respectively.  Some motor controllers support this function, although I've found it generally not accurate enough to used in the feedback control loop.
